name: pdfium_bindings
description: This project aims to wrap the complete [Pdfium](https://pdfium.googlesource.com/pdfium/) API in dart, over FFI.
version: 2.0.1
homepage: https://github.com/insinfo/pdfium_bindings

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  ffi: '>=1.1.2 <3.0.0'
  image: ^4.0.0
  path: ^1.8.1

dev_dependencies:
  build_runner: ^2.1.2
  ffigen: any #^2.4.2
  http: any
  lint: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true
        sharedDarwinSource: true
      linux:
        ffiPlugin: true
      macos:
        ffiPlugin: true
        sharedDarwinSource: true
      windows:
        ffiPlugin: true

#dart run ffigen --config ffigen.yaml